language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: loganthatcher-github
    token:
      secure: 5e9fcb13d2ca9de81df51169cc8b810c3cd296a7
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'